markdown: rdiscount
permalink: /:title/
url: http://www.photoneray.com
name: Photone Ray
author: Keyring
qq: 312674525
email: keyrings@163.com / zkeyring@gmail.com
github: keyring
pygments: true
safe: true
paginate: 20
◦truncate: 300
about: "思维停靠的港湾"
