markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough", "with_toc_data"]
permalink: /:title/
url: http://www.photoneray.com
name: Photone Ray
author: Keyring
email: keyrings@163.com | zkeyring@gmail.com
duoshuo: keyring
github: keyring
highlighter: true
safe: true
paginate: 20
truncate: 100
about: "圈钥匙的钥匙圈·思维停靠的港湾"
